<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #444;
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
            background-color: #f5f5f5;
          }
          .container {
            background-color: #fff;
            border-radius: 4px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
            padding: 2rem;
          }
          h1 {
            color: #23282d;
            font-size: 1.8rem;
            margin-bottom: 1rem;
            font-weight: 600;
            border-bottom: 1px solid #eee;
            padding-bottom: 1rem;
          }
          h2 {
            color: #23282d;
            font-size: 1.4rem;
            margin: 1.5rem 0 1rem;
            font-weight: 500;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 1rem;
            border: 1px solid #eee;
            border-radius: 4px;
            overflow: hidden;
          }
          th {
            text-align: left;
            padding: 1rem;
            font-size: 14px;
            font-weight: 600;
            background-color: #f8f9fa;
            color: #32373c;
            border-bottom: 2px solid #2271b1;
          }
          td {
            padding: 0.8rem 1rem;
            border-bottom: 1px solid #f1f1f1;
            font-size: 14px;
            vertical-align: top;
          }
          tr:hover td {
            background-color: #f8f9fa;
          }
          tr:last-child td {
            border-bottom: none;
          }
          .url {
            width: 60%;
            word-break: break-all;
          }
          .lastmod, .changefreq, .priority {
            width: 15%;
          }
          .url a {
            color: #2271b1;
            text-decoration: none;
            font-weight: 500;
          }
          .url a:hover {
            color: #135e96;
            text-decoration: underline;
          }
          .header {
            background-color: #fff;
            padding: 1rem 0;
            margin-bottom: 1rem;
          }
          .desc {
            margin-bottom: 1.5rem;
            color: #666;
            font-size: 14px;
            line-height: 1.5;
          }
          .stats {
            background-color: #f0f6fc;
            border-left: 4px solid #2271b1;
            padding: 12px 15px;
            margin-bottom: 1.5rem;
            border-radius: 3px;
          }
          .footer {
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid #eee;
            font-size: 13px;
            color: #666;
            text-align: center;
          }
          .xml-tag {
            color: #2271b1;
            font-family: monospace;
            background: #f0f6fc;
            padding: 0.2rem 0.4rem;
            border-radius: 3px;
            font-size: 90%;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>XML Sitemap</h1>
            <p class="desc">This is an XML Sitemap, meant for consumption by search engines like Google or Bing.</p>
          </div>
          
          <xsl:apply-templates select="sitemap:sitemapindex"/>
          <xsl:apply-templates select="sitemap:urlset"/>
          
          <div class="footer">
            <p>Generated by Advanced XML Sitemaps Plugin for WordPress by Abdul Rehman Waheed</p>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
  
  <!-- Sitemap Index Template -->
  <xsl:template match="sitemap:sitemapindex">
    <h2>Sitemap Index</h2>
    <div class="stats">
      This sitemap index contains <strong><xsl:value-of select="count(sitemap:sitemap)"/></strong> sitemaps.
    </div>
    
    <table id="sitemap">
      <tr>
        <th class="url">URL</th>
        <th class="lastmod">Last Modified</th>
      </tr>
      <xsl:for-each select="sitemap:sitemap">
        <tr>
          <td class="url">
            <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
          </td>
          <td class="lastmod">
            <xsl:value-of select="sitemap:lastmod"/>
          </td>
        </tr>
      </xsl:for-each>
    </table>
  </xsl:template>
  
  <!-- URL Set Template -->
  <xsl:template match="sitemap:urlset">
    <h2>URL Sitemap</h2>
    <div class="stats">
      This sitemap contains <strong><xsl:value-of select="count(sitemap:url)"/></strong> URLs.
    </div>
    
    <table id="sitemap">
      <tr>
        <th class="url">URL</th>
        <th class="lastmod">Last Modified</th>
        <th class="changefreq">Change Frequency</th>
        <th class="priority">Priority</th>
      </tr>
      <xsl:for-each select="sitemap:url">
        <tr>
          <td class="url">
            <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
          </td>
          <td class="lastmod">
            <xsl:value-of select="sitemap:lastmod"/>
          </td>
          <td class="changefreq">
            <xsl:value-of select="sitemap:changefreq"/>
          </td>
          <td class="priority">
            <xsl:value-of select="sitemap:priority"/>
          </td>
        </tr>
      </xsl:for-each>
    </table>
  </xsl:template>
</xsl:stylesheet>